extract t4ce1
useridalias ogg1 domain orclpdb
exttrail t4/cd/n1
SOURCECATALOG ORCLPDB
FETCHOPTIONS NOUSESNAPSHOT
GETTRUNCATES
NOCOMPRESSUPDATES

table ZHTOS.SBC_FEE_TYPE
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_FEE_TYPE_ITEM
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_FEE_ITEM
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_FEE_MODE
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_FEE_ELEMENT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.FEE_ELE_ATTR
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_FEE_MODE_ELEMENT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.FEE_BILL_DETAIL
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_AGREEMENT_TARRIF
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.FEE_BILL
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.FEE_BILL_DET_REL
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_AGREEMENT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SHIP_VISIT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.YARD_UNIT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.GATE_WORK_UNIT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SHIP_UNIT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.YARD_WORK_UNIT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_CUSTOMER
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SHIP_WORK_UNIT
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_EQUIP_TYPE
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SBC_EQUIP
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
table ZHTOS.SHIP_CRANE_ASSIGN
TOKENS
(FND_SCN = @GETENV('TRANSACTION','CSN')
FND_ROW_RANK = @GETENV('RECORD','RSN')
FND_ROW_ID = @GETENV('RECORD','ROWID')
FND_COMMIT_DATE=@GETENV('GGHEADER','COMMITTIMESTAMP')
FND_BEF_AFT=@GETENV ('GGHEADER', 'BEFOREAFTERINDICATOR')
FND_EXT_TIME=@date('yyyy-mm-dd hh:mi:ss.ffffff', 'JTS',@getenv ('JULIANTIMESTAMP'))
FND_DML_TYPE=@GETENV('GGHEADER','OPTYPE'));
